backend:
  name: github
  repo: Parlons2Cash/parlonscash.pro   # ton dépôt exact
  branch: main                         # la branche principale

media_folder: "static/uploads"          # où les images seront stockées
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Articles du blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
