backend:
  name: github
  repo: Parlons2Cash/parlonscash.pro   # remplace par ton dépôt exact si différent
  branch: main

media_folder: "static/uploads"   # où les images seront enregistrées
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Articles de blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
